package edu.tamu.webtoxpi.dao.model;
// Generated Sep 5, 2015 1:43:34 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rowtypes generated by hbm2java
 */
public class Rowtypes implements java.io.Serializable
{

	private int id;
	private String code;
	private String name;
	private String notes;
	private Integer color;
	private Date registereddt;
	private Date lastvisitdt;
	private Set rowheaderses = new HashSet(0);

	public Rowtypes()
	{
	}

	public Rowtypes(int id, String code, String name, Date registereddt, Date lastvisitdt)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
	}

	public Rowtypes(int id, String code, String name, String notes, Integer color, Date registereddt, Date lastvisitdt, Set rowheaderses)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.notes = notes;
		this.color = color;
		this.registereddt = registereddt;
		this.lastvisitdt = lastvisitdt;
		this.rowheaderses = rowheaderses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Integer getColor()
	{
		return this.color;
	}

	public void setColor(Integer color)
	{
		this.color = color;
	}

	public Date getRegistereddt()
	{
		return this.registereddt;
	}

	public void setRegistereddt(Date registereddt)
	{
		this.registereddt = registereddt;
	}

	public Date getLastvisitdt()
	{
		return this.lastvisitdt;
	}

	public void setLastvisitdt(Date lastvisitdt)
	{
		this.lastvisitdt = lastvisitdt;
	}

	public Set getRowheaderses()
	{
		return this.rowheaderses;
	}

	public void setRowheaderses(Set rowheaderses)
	{
		this.rowheaderses = rowheaderses;
	}

}
