package edu.tamu.webtoxpi.dao.entity;
// Generated Sep 5, 2015 12:29:29 PM by Hibernate Tools 4.3.1.Final

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable
{

	private int id;
	private Results results;
	private Rowheaders rowheaders;

	public Orders()
	{
	}

	public Orders(int id)
	{
		this.id = id;
	}

	public Orders(int id, Results results, Rowheaders rowheaders)
	{
		this.id = id;
		this.results = results;
		this.rowheaders = rowheaders;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Results getResults()
	{
		return this.results;
	}

	public void setResults(Results results)
	{
		this.results = results;
	}

	public Rowheaders getRowheaders()
	{
		return this.rowheaders;
	}

	public void setRowheaders(Rowheaders rowheaders)
	{
		this.rowheaders = rowheaders;
	}

}
